spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: class:/templates/
    suffix: .html
    mode: HTML
  cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  type-aliases-package: com.yinhai.Bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml


server:
  port: 8080
